FROM python:3.10.4-buster
WORKDIR /root/src

RUN pip install "numpy==1.22.3"
RUN pip install "pandas==1.4.2"
RUN pip install "matplotlib==3.5.1"
RUN pip install "ipykernel==6.13.0"

CMD tail -f /dev/null